hw3 -- MADE
made-mlops-2022/nikita_orlov pull request #3
Opened 2022-12-04 17:16 UTC by NikOrlov

0. Airflow поднят.
1. Даг для подготовки данных реализован.
Единственное, нужно скачать из прошлой домашки [датасет](https://www.kaggle.com/datasets/cherngs/heart-disease-cleveland-uci) и положить его в airflow_ml_dags/images/generate_data/heart_cleveland_upload.csv
Генератор датасетов каждый день берет произвольный набор строк из исходного. (5 баллов)
2. Даг с обучением реализован (10 баллов)
3. Даг с использованием модели реализован (5 баллов)
4. Все логические даги делал через DockerOperator (есть искусственные EmptyOperator - start, end,  добавил для солидности, чтобы была не одна таска) (10 баллов)
5. Самооценка  (1 балл)
Суммарное количество баллов: 5 + 10 + 5 + 10 + 1 = 31 балл
![generate_data_dag](https://user-images.githubusercontent.com/21123064/205505312-81725679-c865-439b-8ce2-f9694ab8955e.png)
![train_dag](https://user-images.githubusercontent.com/21123064/205505319-0e8b1c57-a188-4ba7-8cfd-67b5a62826b5.png)
![predict_dag](https://user-images.githubusercontent.com/21123064/205505326-5baa85c9-7d24-4741-8516-6a0d15c1e288.png)
![all_dags](https://user-images.githubusercontent.com/21123064/205505329-ee92f4ff-28e9-4157-af15-60f67ddab435.png)
![airflow_var](https://user-images.githubusercontent.com/21123064/205505333-21f7bfde-70cc-4de6-8da1-673cb14359bd.png)

2022-12-07 08:24 UTC, bulaevvi requested changes
В задании указано: "Чтобы получить баллы, сделайте скриншоты списка всех дагов и каждого графа по отдельности (в исполненном без ошибок виде) и прикрепите их в описание пулл реквеста". У Вас есть общий скриншот, но нет скриншотов отдельных трех дагов. См. пример скриншотов в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-07 10:26 UTC, bulaevvi commented
Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-08 07:52 UTC, NikOrlov commented
Доброе утро, в прикрепленных ранее скриншотах выбрал в Airflow вкладку "Grid" вместо "Graph", чтобы продемонстрировать факт успешной работы не только последнего запуска, а всех запусков (все квадратики зеленые).
Прикрепляю ниже скриншоты формата "Graph" как в примере дискорда:
![generate_data_dag](https://user-images.githubusercontent.com/21123064/206389836-1422934f-4186-4209-aaee-22e9bbc2ac8a.png)
![predict_dag](https://user-images.githubusercontent.com/21123064/206389845-3577ec23-273c-48fe-8052-debb33e95f72.png)
![train_dag](https://user-images.githubusercontent.com/21123064/206389850-768dc87f-2393-4137-84f5-ff8e200150f4.png)

2022-12-08 08:14 UTC, bulaevvi approved these changes
Итого 31 балл. Делайте merge

2022-12-08 11:27 UTC, NikOrlov commented
Спасибо

2022-12-08 11:27 UTC, merged